on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on manylinux2014_${{ matrix.arch }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - base_image: quay.io/pypa/manylinux2014_x86_64
            arch: x86_64
          - base_image: quay.io/pypa/manylinux2014_ppc64le
            arch: ppc64le

    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          ref: develop
          path: spack

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: build_manylinux2014_${{ matrix.arch }}
          save-always: true

      - name: Run Build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          base_image: ${{ matrix.base_image }}

          githubToken: $ {{ github.token }}

          setup: |
            mkdir -p ~/.ccache

          install: |
            yum update -y
            yum install ccache

          dockerRunArgs: |
            --volume "${HOME}/.ccache:/root/.ccache"

          env: |
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_IMAGE: ${{ matrix.base_image }}

          run: |
            # Spack environment variables
            export PATH=$PATH:$(pwd)/spack/bin
            export SPACK_COLOR=always
            export SPACK_DISABLE_LOCAL_CONFIG=1
            export SPACK_PYTHON=/opt/python/cp312-cp312/bin/python

            # Find compilers
            spack -e . compiler find --mixed-toolchain

            # Login
            spack -e . mirror set \
            --oci-username $GITHUB_ACTOR --oci-password $GITHUB_TOKEN local-buildcache

            # Concretize
            spack -e . concretize --fresh

            # Spack Install 
            spack -e . install --no-check-signature

            # Push packages and update index
            spack -e . buildcache push --base-image $BASE_IMAGE --update-index local-buildcache
